os: Visual Studio 2015
version: "{build}"
build: off
platform: x64
environment:
  matrix:
  - nodejs_version: "0.12"
    nodejs_arch: "x86"
  - nodejs_version: "0.12"
    nodejs_arch: "x64"
  - nodejs_version: "4"
    nodejs_arch: "x86"
  - nodejs_version: "4"
    nodejs_arch: "x64"
  - nodejs_version: "5"
    nodejs_arch: "x86"
  - nodejs_version: "5"
    nodejs_arch: "x64"
install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
  - npm install
test_script:
  - npm test
